apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-deployment
  template:
    metadata:
      labels:
        app: postgres-deployment
    spec:
      initContainers:
        - name: init-db
          image: postgres:16
          envFrom:
            - secretRef:
                name: postgres-secret
          command: [ "sh", "-c" ]
          args:
            - |
              DB_EXISTS=$(psql -U "$POSTGRES_USER" -tc "SELECT 1 FROM pg_database WHERE datname = '$POSTGRES_DB'")

              # If the database does not exist, create it
              if [ "$DB_EXISTS" != "1" ]; then
                echo "Database $POSTGRES_DB does not exist. Creating it..."
                psql -U "$POSTGRES_USER" -c "CREATE DATABASE \"$POSTGRES_DB\";"
              else
                echo "Database $POSTGRES_DB already exists."
              fi
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
