apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-deployment
  template:
    metadata:
      labels:
        app: postgres-deployment
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
            - configMapRef:
                name: postgres-configmap
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          lifecycle:
            postStart:
              exec:
                command: [ "sh", "-c", "
                  until pg_isready -h localhost -p 5432; do
                    echo 'Waiting for PostgreSQL to start...';
                    sleep 1;
                  done;

                  echo 'PostgreSQL started.';
                  
                  DB_EXISTS=$(psql -tc \"SELECT 1 FROM pg_database WHERE datname = '$POSTGRES_DB'\")
                  if [ \"$DB_EXISTS\" != \"1\" ]; then
                    echo 'Database $POSTGRES_DB does not exist. Creating it...';
                    psql -c \"CREATE DATABASE \\\"$POSTGRES_DB\\\";\"
                  else
                    echo 'Database $POSTGRES_DB already exists.';
                  fi
                " ]
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
