apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-cert
  namespace: postgres
spec:
  secretName: postgres-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  dnsNames:
    - postgres.rutgerpronk.com
    - postgres-service.postgres.svc.cluster.local
  issuerRef:
    name: production
    kind: ClusterIssuer

