apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-certificate
  namespace: postgres-${ENVIRONMENT}
spec:
  secretName: postgres-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  dnsNames:
    - postgres-${ENVIRONMENT}.${BASE_DOMAIN}
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io