apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: postgres-ingress
  namespace: postgres-${ENVIRONMENT}
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - postgres-${ENVIRONMENT}.${BASE_DOMAIN}
    secretName: postgres-tls
  rules:
  - host: postgres-${ENVIRONMENT}.${BASE_DOMAIN}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: postgres-service
            port:
              number: 5432