apiVersion: batch/v1
kind: Job
metadata:
  name: ${SERVICE_NAME}-init-database
spec:
  template:
    spec:
      containers:
      - name: create-db
        image: postgres:16
        command:
        - /bin/sh
        - -c
        - |
          echo "Checking if database ${DB_NAME} exists..."
          EXISTS=$(PGPASSWORD=$POSTGRES_PASSWORD psql -h ${DB_HOST} \
            -U $POSTGRES_USER \
            -d postgres \
            -t \
            -c "SELECT 1 FROM pg_database WHERE datname = '${DB_NAME}';")
          
          if [ -z "$EXISTS" ]; then
            echo "Database ${DB_NAME} does not exist. Creating..."
          
            PGPASSWORD=$POSTGRES_PASSWORD psql -h ${DB_HOST} \
              -U $POSTGRES_USER \
              -d postgres \
              -c "CREATE DATABASE ${DB_NAME};"
            
            if [ $? -eq 0 ]; then
              echo "Database ${DB_NAME} created successfully"
            else
              echo "Failed to create database ${DB_NAME}"
              exit 1
            fi
          else
            echo "Database ${DB_NAME} already exists"
          fi
        env:
          - name: DB_NAME
            value: ${DB_NAME}
          - name: DB_HOST
            value: ${DB_HOST}
        envFrom:
          - secretRef:
              name: postgres-secret