name: Deploy

on:
  push:
    tags:
      - '*'

env:
  APP_NAME: postgres
  POSTGRES_VERSION: 17

jobs:
  deploy-postgres-to-kubernetes:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [ production, test ]
    environment: ${{ matrix.environment }}

    steps:
      - name: Test
        run: |
          echo "Environment: ${{ matrix.environment }}"
          echo "APP_NAME: ${{ env.APP_NAME }}"
          echo "POSTGRES_VERSION: ${{ env.POSTGRES_VERSION }}"
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "GITHUB_REF_NAME: ${{ github.ref_name }}"
          echo "TEST_VAR: ${{ vars.TEST_VAR }}"
          exit 1

      - uses: actions/checkout@v4

      - name: Install envsubst
        run: sudo apt-get update && sudo apt-get install -y gettext-base

      - uses: azure/setup-kubectl@v4
        with:
          version: 'v1.31.0'

      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v4.0.1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Install yq
        uses: Makepad-fr/setup-yq-action@v1.0.0
        with:
          version: "4.44.2"

      - name: Insert environment variables into Kubernetes files
        run: |
          FILES=$(ls postgres/deploy/*.yaml | tr '\n' ' ')
          
          for FILE in $FILES; do
            echo "Processing $FILE"
          
            envsubst < $FILE > /tmp/envsubst || exit 1
          
            mv /tmp/envsubst $FILE || exit 1
          done
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          TAG_NAME: ${{ github.ref_name }}

      - name: Check if secret already exists
        run: |
          if [ -f postgres/deploy/secret.yaml ]; then
            SECRET_NAME=$(yq '.metadata.name' postgres/deploy/secret.yaml)
            SECRET_NAMESPACE=$(yq '.metadata.namespace' postgres/deploy/secret.yaml)

            if kubectl get secret $SECRET_NAME -n $SECRET_NAMESPACE 2>&1 | grep -q "not found"; then
              echo "Secret $SECRET_NAME does not exist in namespace $SECRET_NAMESPACE, leaving file for deploy step"
            else
              echo "Secret $SECRET_NAME already exists in namespace $SECRET_NAMESPACE, removing file"
              rm postgres/deploy/secret.yaml
            fi
          fi

      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v5
        with:
          namespace: ${{ env.NAMESPACE }}
          manifests: |
            postgres/deploy/namespace.yaml
            postgres/deploy/
