name: Deploy

on:
  push:
    tags:
      - '*'

jobs:
  deploy-database-to-kubernetes:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install envsubst
        run: sudo apt-get install -y gettext-base

      - uses: azure/setup-kubectl@v4
        with:
          version: 'v1.31.0'

      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v4.0.1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Insert environment variables into Kubernetes files
        run: |
          FILES=$(ls k8s/*.yaml | tr '\n' ' ')
          
          for FILE in $FILES; do
            echo "Processing $FILE"
          
            envsubst < $FILE > /tmp/envsubst || exit 1
          
            mv /tmp/envsubst $FILE || exit 1
          done
        env:
          TAG_NAME: ${{ github.ref_name }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}

      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            k8s/
